### ISSUE TITLE
Telerik.ReportViewer.WebForms

### ISSUE THREAD

**Issue by dannystyle** [towhidulbashar/TelerikReport#1]
CS0433: The type 'Telerik.ReportViewer.WebForms.ReportViewer' exists in both 'c:\Windows\Microsoft.NET\assembly\GAC_MSIL\Telerik.ReportViewer.WebForms\v4.0_10.1.16.615__a9d7983dfcc261be\Telerik.ReportViewer.WebForms.dll' and 'c:\Users\Teser\AppData\Local\Temp\Temporary ASP.NET Files\root\18f20304\a000a56b\assembly\dl3\73c6b502\00e4e1e3_6d2ed101\Telerik.ReportViewer.WebForms.DLL'

 private global::Telerik.ReportViewer.WebForms.ReportViewer @__BuildControlpersonReportViewer() {

**Comment by towhidulbashar** [comment]
Your environment is not referencing correct version of Telerik.ReportViewer.WebForms.dll. Right click this dll, then from Property correct the reference link.
